server:
  port: 8080
spring:
  application:
    name: sboot-planets-api
app:
  build:
    version: v1
    domain: planet
---
spring:
  profiles:
    active: local
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:mysql://localhost:3306/planets
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hikari:
      maximum-pool-size: 5 #Máximo de conexões do pool
      connection-timeout: 300 #Tempo máximo de espera por uma conexão
      minimum-idle: 2 #Minimo de conexões ociosas
      idle-timeout: 1000 #Maximo idle time for connection
      max-life-time: 360000 #Tempo máximo de duração de uma conexão



